name: windows

on:
  push:
    tags:
      - "v*"
  pull_request:
    tags:
      - "v*"

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:

    runs-on: windows-2022
    if: github.repository == 'hzqst/MetaHookSv'

    steps:
      - uses: hzqst/checkout@v2.3.4

      - name: Init dependencies
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: git submodule update --init --recursive
        shell: cmd

      - name: Build MetaHook and Plugins
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: scripts\build-MetaHook.bat
        shell: cmd

      - name: Build Plugins
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: scripts\build-Plugins.bat
        shell: cmd

      - name: Create Output directory
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: mkdir Output
        shell: cmd

      - name: Copy Build to Output
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir "Output\Build"
          xcopy "Build" "Output\Build" /y /e
        shell: cmd
        
      - name: Copy SteamAppsLocation to Output
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir "Output\tools"
          copy "tools\SteamAppsLocation.exe" "Output\tools" /y
          copy "tools\steam_appid.txt" "Output\tools" /y
          copy "tools\steam_api.dll" "Output\tools" /y
        shell: cmd

      - name: Copy install bat to Output
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir "Output\scripts"
          copy "scripts\install-to-BlueShift.bat" "Output\scripts" /y
          copy "scripts\install-to-ConditionZero.bat" "Output\scripts" /y
          copy "scripts\install-to-CounterStrike.bat" "Output\scripts" /y
          copy "scripts\install-to-CSCZDeletedScenes.bat" "Output\scripts" /y
          copy "scripts\install-to-DayOfDefeat.bat" "Output\scripts" /y
          copy "scripts\install-to-Echoes.bat" "Output\scripts" /y
          copy "scripts\install-to-HalfLife.bat" "Output\scripts" /y
          copy "scripts\install-to-HalfLifeUpdated.bat" "Output\scripts" /y
          copy "scripts\install-to-OpposingForce.bat" "Output\scripts" /y
          copy "scripts\install-to-SvenCoop.bat" "Output\scripts" /y
        shell: cmd

      - name: Zipping All
        uses: vimtor/action-zip@v1
        with:
          files: Output/
          dest: MetaHookSv-windows-x86.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: MetaHookSv-${{ github.ref }}
          files: |
            MetaHookSv-windows-x86.zip
